// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcyCKuuWkVqYWxNZ8kUTZ-3Wuql2fqfuU',
    appId: '1:1061629660004:android:72427bc730ce51a297c871',
    messagingSenderId: '1061629660004',
    projectId: 'currenta-prod',
    storageBucket: 'currenta-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYLHK7SJpuAnT2T4d7jMEEzEAf6IvVV2c',
    appId: '1:1061629660004:ios:cac40c799f2698c297c871',
    messagingSenderId: '1061629660004',
    projectId: 'currenta-prod',
    storageBucket: 'currenta-prod.firebasestorage.app',
    androidClientId: '1061629660004-nffm75ich0b93d70ksiqo66cqtjgf08s.apps.googleusercontent.com',
    iosClientId: '1061629660004-hdk9lsdp52e1lk7523rkrk17vahd384i.apps.googleusercontent.com',
    iosBundleId: 'com.currenta.app',
  );
}
